config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :blogposts
  # You can have the root of your site routed with "root"
  root 'blogposts#index'

  namespace :api do
    namespace :v1 do
      resources :blogposts
    end
  end
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true

  default_scope { order("created_at desc") }
end

app/models/food_group.rb
class FoodGroup < ActiveRecord::Base
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipes, through: :ingredient_units
end

app/models/ingredient_unit.rb
class IngredientUnit < ActiveRecord::Base
  belongs_to :ingredients
  belongs_to :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients, through: :ingredient_units

  validates :title, presence: true
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :ingredient_unit
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blogposts
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/blogposts_controller.rb
class Api::V1::BlogpostsController < Api::V1::BaseController
  def index
    respond_with Blogpost.all
  end

  def create
    respond_with :api, :v1, Blogpost.create(blogpost_params)
  end

  def destroy
    respond_with Blogpost.destroy(params[:id])
  end

  def update
    respond_with Blogpost.update(params[:id], blogpost_params)
  end

 private

  def blogpost_params
    params.require(:blogpost).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  def index
    @blogs = Blogpost.all
  end

  def new
    @blog = Blogpost.new
  end

  def create
    @blog = Blogpost.new(blogpost_params)

    if @blog.save
      flash[:success] = "it saved"
      redirect_to :back
    else
      flash[:danger] = "it failed to save"
      redirect_to :back
    end
  end

  def show
    @blog = Blogpost.find(params[:id])
  end

  def edit
    @blog = Blogpost.find(params[:id])
  end

  def update
    @blog = Blogpost.find(params[:id])
    @blog.update_attributes(blogpost_params)

    flash[:success] = "Successfully updated."
    redirect_to blogposts_path
  end

  private

  def blogpost_params
    params.require(:blogpost).permit(:title, :body, :user_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @ingredient = Ingredient.new
  end

  def create
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      flash[:success] = "Recipe has been created"
      redirect_to :back
    else
      flash[:warning] = "Recipe failed to save"
      redirect_to :back
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title,
                                   :directions,
                                   :baking_time,
                                   :baking_temperature,
                                   :servings)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogposts/_blogform.html.erb
<%= form_for @blog do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :body %>
  <%= f.text_field :body, class: "form-control" %>

  <%= f.label :user_id %>
  <%= f.text_field :user_id, class: "form-control" %>
  <br>
  <%= f.submit "Create New Post", class: "btn btn-default" %>
<% end %>

app/views/blogposts/edit.html.erb
<%= render "blogposts/blogform" %>

app/views/blogposts/index.html.erb
<%= react_component 'AllBlogs' %>
<% @blogs.each do |blog| %>
  <h4><%= link_to blog.title, blogpost_path(blog) %></h4>
  <p><%= blog.body %></p>
<% end %>

app/views/blogposts/new.html.erb
<h3>New Post</h3>
<%= render "blogposts/blogform" %>

app/views/blogposts/show.html.erb
<h4><%= @blog.title.titleize %></h4>
<p><%= @blog.body %></p>

<%= link_to "Edit", edit_blogpost_path(@blog), class: "btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mile High Miriam</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'partials/header' %>
  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <div class="alert alert-#{key}"><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Mile High Miriam</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Blog", blogposts_path %></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Learn More<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Get the Newsletter</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Write New Blog", new_blogpost_path %></li>
            <li><a href="#">Log in</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/recipes/new.html.erb
<%= form_for @recipe, url: {action: "create"} do |f| %>
  <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :directions %>
  <%= f.text_field :directions %>
  </p>
  <p>
  <%= f.label :baking_time %>
  <%= f.text_field :baking_time %> minutes.
  </p>
  <p>
  <%= f.label :baking_temperature %>
  <%= f.text_field :baking_temperature %> degrees fahrenheit.
  </p>
  <p>
  <%= f.label :servings %>
  <%= f.text_field :servings %>
  </p>
  <%= f.submit "Create Recipe", class: "btn btn-success" %>
<% end %>